# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b02aa692299f88785fc194988795ffd78dda85249ff9ad3df6e8b91a953f251f6761158018f30dde766451516a3c7ab92565484555511eb9910450d2bd19725

test:
  secret_key_base: 45ef22c5a11fa8a173bbf78ba6921406e675731ebf6fb01f1356fa2b3dd1fbc1eb637b4fad0918674583a33c1b32eb82de74fc2a8af7a29935f25fac47de173e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
